version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: ["5433:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: { context: ./backend }
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_MILVUS_HOST: standalone
      APP_MILVUS_PORT: 19530
    depends_on:
      postgres:
        condition: service_started
      standalone:
        condition: service_healthy
    ports: ["8080:8080"]

  frontend:
    build: { context: ./frontend }
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    depends_on:
      - backend
    ports: ["3000:3000"]

volumes:
  pgdata: